# Generated by Django 4.1.3 on 2022-11-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invnumber', models.IntegerField()),
                ('category', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=225)),
                ('condition', models.CharField(max_length=225)),
                ('checkedout', models.CharField(max_length=3)),
            ],
        ),
    ]
