# Generated by Django 4.1.3 on 2022-12-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='date_in',
            field=models.DateField(blank=True, null=True),
        ),
    ]
