# Generated by Django 4.1.3 on 2022-11-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_equipment_checkedout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientID', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='checkedout',
            field=models.CharField(max_length=5),
        ),
    ]
