# Generated by Django 4.1.3 on 2022-11-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_clients_alter_equipment_checkedout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='clientID',
            field=models.CharField(max_length=20),
        ),
    ]
