# Generated by Django 4.1.3 on 2022-12-02 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_clients_clientid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Loans',
        ),
    ]
