# Generated by Django 4.1.3 on 2022-12-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loans_date_in_alter_loans_date_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='date_in',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='date_out',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='equip_id',
            field=models.IntegerField(blank=True),
        ),
    ]
