# Generated by Django 4.1.3 on 2022-12-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loans_date_in_alter_loans_date_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='checkedout',
            field=models.BooleanField(),
        ),
    ]
